# Generated by Django 3.2.15 on 2022-10-27 12:00

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_contentcard_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Nickname',
        ),
        migrations.AlterField(
            model_name='contentcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[blog.models.validate_max_size], verbose_name='イメージ画像'),
        ),
    ]
